CREATE SCHEMA rsoi_disp DEFAULT CHARACTER SET utf8 ;

-- Таблица зарегистрированных пользователей
create table rsoi_disp.USER (
	USER_ID BIGINT NOT NULL AUTO_INCREMENT,
	USER_LOGIN VARCHAR(100) NOT NULL,
	USER_PWD VARCHAR(100) NOT NULL,
	USER_NAME VARCHAR(100),
	USER_LNAME VARCHAR(100),
	USER_MNAME VARCHAR(100), 
	LAST_UPDATE_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY(USER_ID),
	INDEX USER_LOGIN_IDX (USER_ID ASC) )


	COMMENT = 'Зарегистрированные пользователи диспетчерской АИС';
    
    
-- Незарегистрированные пользователи диспетчерской АИС
create table rsoi_disp.GUEST (
	GUEST_ID BIGINT NOT NULL AUTO_INCREMENT, 
	GUEST_CODE VARCHAR(200) NOT NULL,
	LAST_UPDATE_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY(GUEST_ID),
	INDEX GUEST_CODE_IDX(GUEST_CODE ASC))

COMMENT = 'Незарегистрированные пользователи Диспетчерской АИС'; 


-- Детали заявки
CREATE TABLE RSOI_DISP.ORDER_DETAILS (
	ORDER_DETAIL_ID BIGINT NOT NULL AUTO_INCREMENT,
	ADDRESS VARCHAR(500) NOT NULL,
	DELIVERY_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	KM_PRICE DOUBLE,
	MIN_PRICE DOUBLE,
	ORDER_STATUS VARCHAR(100) NOT NULL,
	COORDINATES VARCHAR(250),
	
	PRIMARY KEY(ORDER_DETAIL_ID),
	INDEX DELIVERY_TIME_IDX(DELIVERY_TIME ASC),
	INDEX STATUS_IDX(ORDER_STATUS ASC)
)

COMMENT = 'Детали заявки';

-- Подтвержденные заявки зарегистрированных пользователей
CREATE TABLE  RSOI_DISP.USER_ORDERS (
	ORDER_ID BIGINT NOT NULL AUTO_INCREMENT,
	ORDER_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	USER_ID BIGINT NOT NULL,
	ORDER_DETAIL_ID BIGINT NOT NULL,

	PRIMARY KEY(ORDER_ID),
	CONSTRAINT FOREIGN KEY (USER_ID) REFERENCES RSOI_DISP.USER (USER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FOREIGN KEY (ORDER_DETAIL_ID) REFERENCES RSOI_DISP.ORDER_DETAILS (ORDER_DETAIL_ID) ON DELETE CASCADE ON UPDATE CASCADE,

	INDEX USER_ID_IDX(USER_ID ASC),
	INDEX ORDER_DETAIL_ID_IDX(ORDER_DETAIL_ID ASC)
)

COMMENT  = 'Подтвержденные заявки зарегистрированных пользователей';

-- Подтвержденные заказа незарегистрированных пользователей
CREATE TABLE RSOI_DISP.GUEST_ORDERS (
	ORDER_ID BIGINT NOT NULL AUTO_INCREMENT,
	ORDER_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	GUEST_ID BIGINT NOT NULL,
	ORDER_DETAIL_ID BIGINT NOT NULL,

	PRIMARY KEY(ORDER_ID),
	CONSTRAINT FOREIGN KEY (GUEST_ID) REFERENCES RSOI_DISP.GUEST (GUEST_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FOREIGN KEY (ORDER_DETAIL_ID) REFERENCES RSOI_DISP.ORDER_DETAILS (ORDER_DETAIL_ID) ON DELETE CASCADE ON UPDATE CASCADE,

	INDEX GUEST_ID_IDX(GUEST_ID ASC),
	INDEX ORDER_DETAIL_ID_IDX(ORDER_DETAIL_ID ASC)
)

COMMENT = 'Подтвержденные заказа незарегистрированных пользователей';

-- Поступившие и еще не подтвержденные заявки пользователей
CREATE TABLE RSOI_DISP.APPLICATION (
	APPLICATION_ID BIGINT NOT NULL AUTO_INCREMENT,
	APPLICATION_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	APPLICATION_ST VARCHAR(50) NOT NULL,
	REQUESTER_ID BIGINT NOT NULL,
	ORDER_DETAIL_ID BIGINT NOT NULL,
	USER_INDENTIFIER CHAR(1),

	PRIMARY KEY(APPLICATION_ID),
	CONSTRAINT FOREIGN KEY (REQUESTER_ID) REFERENCES RSOI_DISP.USER_ORDERS (USER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FOREIGN KEY (REQUESTER_ID) REFERENCES RSOI_DISP.GUEST_ORDERS (GUEST_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FOREIGN KEY (ORDER_DETAIL_ID) REFERENCES RSOI_DISP.ORDER_DETAILS (ORDER_DETAIL_ID) ON DELETE CASCADE ON UPDATE CASCADE
)

COMMENT 'Поступившие и еще не подтвержденные заявки пользователей';