
package ru.arkuzmin.dais.model;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DAISWebService", targetNamespace = "http://model.dais.arkuzmin.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DAISWebService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns ru.arkuzmin.dais.model.Status
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://model.dais.arkuzmin.ru/", className = "ru.arkuzmin.dais.model.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://model.dais.arkuzmin.ru/", className = "ru.arkuzmin.dais.model.GetStatusResponse")
    public Status getStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerNewUser", targetNamespace = "http://model.dais.arkuzmin.ru/", className = "ru.arkuzmin.dais.model.RegisterNewUser")
    @ResponseWrapper(localName = "registerNewUserResponse", targetNamespace = "http://model.dais.arkuzmin.ru/", className = "ru.arkuzmin.dais.model.RegisterNewUserResponse")
    public boolean registerNewUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<ru.arkuzmin.dais.model.Order>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserHistory", targetNamespace = "http://model.dais.arkuzmin.ru/", className = "ru.arkuzmin.dais.model.GetUserHistory")
    @ResponseWrapper(localName = "getUserHistoryResponse", targetNamespace = "http://model.dais.arkuzmin.ru/", className = "ru.arkuzmin.dais.model.GetUserHistoryResponse")
    public List<Order> getUserHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns ru.arkuzmin.dais.model.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authorizeUser", targetNamespace = "http://model.dais.arkuzmin.ru/", className = "ru.arkuzmin.dais.model.AuthorizeUser")
    @ResponseWrapper(localName = "authorizeUserResponse", targetNamespace = "http://model.dais.arkuzmin.ru/", className = "ru.arkuzmin.dais.model.AuthorizeUserResponse")
    public User authorizeUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUserApplication", targetNamespace = "http://model.dais.arkuzmin.ru/", className = "ru.arkuzmin.dais.model.AddUserApplication")
    @ResponseWrapper(localName = "addUserApplicationResponse", targetNamespace = "http://model.dais.arkuzmin.ru/", className = "ru.arkuzmin.dais.model.AddUserApplicationResponse")
    public boolean addUserApplication(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Order arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmApplication", targetNamespace = "http://model.dais.arkuzmin.ru/", className = "ru.arkuzmin.dais.model.ConfirmApplication")
    @ResponseWrapper(localName = "confirmApplicationResponse", targetNamespace = "http://model.dais.arkuzmin.ru/", className = "ru.arkuzmin.dais.model.ConfirmApplicationResponse")
    public boolean confirmApplication(
        @WebParam(name = "arg0", targetNamespace = "")
        Order arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addGuestApplication", targetNamespace = "http://model.dais.arkuzmin.ru/", className = "ru.arkuzmin.dais.model.AddGuestApplication")
    @ResponseWrapper(localName = "addGuestApplicationResponse", targetNamespace = "http://model.dais.arkuzmin.ru/", className = "ru.arkuzmin.dais.model.AddGuestApplicationResponse")
    public String addGuestApplication(
        @WebParam(name = "arg0", targetNamespace = "")
        Order arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelOrder", targetNamespace = "http://model.dais.arkuzmin.ru/", className = "ru.arkuzmin.dais.model.CancelOrder")
    @ResponseWrapper(localName = "cancelOrderResponse", targetNamespace = "http://model.dais.arkuzmin.ru/", className = "ru.arkuzmin.dais.model.CancelOrderResponse")
    public boolean cancelOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        Order arg0);

}
