CREATE SCHEMA rsoi_disp DEFAULT CHARACTER SET utf8 ;

create table rsoi_disp.taxiparks (
  taxipark_guid varchar(200) not null,
  taxipark_queue varchar(100) not null,
  
  primary key(taxipark_guid)
);

insert into rsoi_disp.taxiparks (taxipark_guid, taxipark_queue) values ('947a24f8-ead8-4820-984a-108b241bdbbc', 'TAXIPARK1.DISP.IN');
insert into rsoi_disp.taxiparks (taxipark_guid, taxipark_queue) values ('8113c1a7-75d8-4c3a-9757-5d5dccf26a41', 'TAXIPARK2.DISP.IN');

create table rsoi_disp.USER (
	USER_GUID VARCHAR(200) NOT NULL,
	USER_LOGIN VARCHAR(100) NOT NULL,
	USER_PWD VARCHAR(100) NOT NULL,
	USER_NAME VARCHAR(100),
	USER_LNAME VARCHAR(100),
	USER_MNAME VARCHAR(100), 
	LAST_UPDATE_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY(USER_GUID),
	INDEX USER_LOGIN_IDX (USER_LOGIN ASC) );
    
ALTER TABLE RSOI_DISP.USER ADD UNIQUE (USER_LOGIN);

create table rsoi_disp.GUEST (
	GUEST_GUID VARCHAR(200) NOT NULL, 
	GUEST_CODE VARCHAR(200) NOT NULL,
	LAST_UPDATE_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY(GUEST_GUID),
	INDEX GUEST_CODE_IDX(GUEST_CODE ASC)); 


CREATE TABLE RSOI_DISP.ORDER_DETAILS (
	ORDER_DETAIL_GUID VARCHAR(200) NOT NULL,
	ADDRESS VARCHAR(500) NOT NULL,
	DELIVERY_TIME TIMESTAMP NOT NULL,
	KM_PRICE DOUBLE,
	MIN_PRICE DOUBLE,
  COMFORT_CLASS VARCHAR(100),
	ORDER_STATUS VARCHAR(100) NOT NULL,
  STATUS_DESCRIPTION VARCHAR(250),
	COORDINATES VARCHAR(250),
	
	PRIMARY KEY(ORDER_DETAIL_GUID),
	INDEX DELIVERY_TIME_IDX(DELIVERY_TIME ASC),
	INDEX STATUS_IDX(ORDER_STATUS ASC)
);


CREATE TABLE  RSOI_DISP.USER_ORDERS (
	ORDER_GUID VARCHAR(200) NOT NULL,
	ORDER_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	USER_GUID VARCHAR(200) NOT NULL,
	ORDER_DETAIL_GUID VARCHAR(200) NOT NULL,

	PRIMARY KEY(ORDER_GUID),
	CONSTRAINT FOREIGN KEY (USER_GUID) REFERENCES RSOI_DISP.USER (USER_GUID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FOREIGN KEY (ORDER_DETAIL_GUID) REFERENCES RSOI_DISP.ORDER_DETAILS (ORDER_DETAIL_GUID) ON DELETE CASCADE ON UPDATE CASCADE,

	INDEX USER_ID_IDX(USER_GUID ASC),
	INDEX ORDER_DETAIL_ID_IDX(ORDER_DETAIL_GUID ASC)
);

CREATE TABLE RSOI_DISP.GUEST_ORDERS (
	ORDER_GUID VARCHAR(200) NOT NULL,
	ORDER_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	GUEST_GUID VARCHAR(200) NOT NULL,
	ORDER_DETAIL_GUID VARCHAR(200) NOT NULL,

	PRIMARY KEY(ORDER_GUID),
	CONSTRAINT FOREIGN KEY (GUEST_GUID) REFERENCES RSOI_DISP.GUEST (GUEST_GUID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FOREIGN KEY (ORDER_DETAIL_GUID) REFERENCES RSOI_DISP.ORDER_DETAILS (ORDER_DETAIL_GUID) ON DELETE CASCADE ON UPDATE CASCADE,

	INDEX GUEST_ID_IDX(GUEST_GUID ASC),
	INDEX ORDER_DETAIL_ID_IDX(ORDER_DETAIL_GUID ASC)
);

CREATE TABLE RSOI_DISP.APPLICATION (
	APPLICATION_GUID VARCHAR(200) NOT NULL,
	APPLICATION_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	APPLICATION_ST VARCHAR(50) NOT NULL,
	REQUESTER_GUID VARCHAR(200) NOT NULL,
	ORDER_DETAIL_GUID VARCHAR(200) NOT NULL,
	USER_IDENTIFIER CHAR(1) NOT NULL,
	taxipark_queue varchar(100) not null,
	taxi_queue varchar(100) not null,

	PRIMARY KEY(APPLICATION_GUID)
);

ALTER TABLE RSOI_DISP.APPLICATION ADD CONSTRAINT REQUESTRER_ORDER_CNSTR UNIQUE (REQUESTER_GUID, ORDER_DETAIL_GUID);


create table rsoi_disp.taxipark_reply (
	application_guid varchar(200) not null,
	taxipark_guid varchar(200) not null,
	reply varchar(100) not null default 'unknown',
	reply_count integer not null default 0,

	constraint unique (application_guid, taxipark_guid)
);

--drop schema rsoi_disp;


