DROP TABLE RSOI_DISP.APPLICATION;
DROP TABLE RSOI_DISP.GUEST_ORDERS;
DROP TABLE  RSOI_DISP.USER_ORDERS;
DROP TABLE RSOI_DISP.ORDER_DETAILS;
DROP table rsoi_disp.GUEST;
DROP table rsoi_disp.USER;
DROP SCHEMA rsoi_disp;